site_name: StorageAccountTools
repo_url: https://github.com/nekroscope/StorageAccountTools
theme: readthedocs
pages:
  - Home: index.md
  - StorageAccountTools Basics:
    - What is StorageAccountTools: about.md
    - Quick Start: Quick-Start-Installation-and-Example.md
  - Acknowledgements: acknowledgements.md
