# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Tony Bulding
# Generated on: 4/1/2018

@{
    RootModule        = 'StorageAccountTools.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '8c46e885-1e4d-471b-b81e-e45802270e89'
    Author            = 'Tony Bulding'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Tony Bulding. All rights reserved.'
    Description       = ''
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

